name: other
on:
  push:
    branches:
      - other
  schedule:
    - cron: "*/1 * * * *" # every 1 minute
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo branch
        run: echo other
