name: Run Multiple Scripts
on:
  push:
    branches: master

jobs:
  script_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run script 1
        run: node script_1.js

      - uses: actions/upload-artifact@v3
        with:
          path: script_1.txt

  script_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          path: script_1.txt

      - name: Run script 2
        run: node script_2.js
