name: other
on:
  # push:
  #   branches:
  #     - other
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { ref: other }

      - name: Run script
        run: npm start
