name: Run Multiple Scripts
on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes
jobs:
  script_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run script 1
        run: node script_1.js

  script_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run script 2
        run: node script_2.js
