name: Master
env:
  API: ${{ secrets.API }}
on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm start
